success:
  fallback: ✅
  id: 1520592853015724082
  animated: false
admin:
  fallback: 👑
  id: 1520592821890060379
  animated: false
ban:
  fallback: null
  id: 1520592822926049320
  animated: false
clueless:
  fallback: null
  id: 1520592825841094918
  animated: false
creator:
  fallback: null
  id: 1520592826545733763
  animated: false
error:
  fallback: ❌
  id: 1520592829229957132
  animated: false
explosion:
  fallback: null
  id: 1520592830408691816
  animated: true
facepalm:
  fallback: null
  id: 1520592831192760421
  animated: true
first:
  fallback: null
  id: 1520592831779966986
  animated: false
forward:
  fallback: null
  id: 1520592832581206176
  animated: false
game_mafia:
  fallback: null
  id: 1520592834493677760
  animated: false
github:
  fallback: null
  id: 1520592835198324807
  animated: false
hmm:
  fallback: null
  id: 1520592836330786958
  animated: false
hnn:
  fallback: null
  id: null
  animated: false
join:
  fallback: null
  id: 1520592837291282492
  animated: false
kick:
  fallback: null
  id: 1520592838218350742
  animated: false
last:
  fallback: null
  id: 1520592839623446589
  animated: false
leave:
  fallback: null
  id: 1520592841074671749
  animated: false
loading:
  fallback: null
  id: 1520592842291150968
  animated: true
playcord:
  fallback: null
  id: 1520592845394677820
  animated: false
pointing:
  fallback: null
  id: 1520592846082670672
  animated: false
ready:
  fallback: null
  id: 1520592847706001431
  animated: false
rematch:
  fallback: null
  id: 1520592848498458665
  animated: false
settings:
  fallback: null
  id: 1520592850335563886
  animated: false
space:
  fallback: null
  id: 1520592851149520957
  animated: false
spectate:
  fallback: null
  id: 1520592852164284486
  animated: false
time:
  fallback: ⏰
  id: 1520592853842137219
  animated: false
timer:
  fallback: ⏱️
  id: 1520592854810886154
  animated: false
user:
  fallback: null
  id: 1520592855406739487
  animated: false
play:
  fallback: ▶️
  id: 1520592844723716286
  animated: false
previous:
  fallback: ◀️
  id: 1520592846770405456
  animated: false
next:
  fallback: ▶️
  id: 1520592843947638964
  animated: false
external_link:
  fallback: 🔗
  id: null
  animated: false
configure:
  fallback: ⚙️
  id: null
  animated: false
tictactoe_x:
  fallback: ❌
  id: null
  animated: false
tictactoe_o:
  fallback: ⭕
  id: null
  animated: false
mafia_villager:
  fallback: 🧑‍🌾
  id: null
  animated: false
mafia_werewolf:
  fallback: 🐺
  id: null
  animated: false
game:
  fallback: null
  id: 1520592833570934795
  animated: false
learn:
  fallback: null
  id: 1520592840269369485
  animated: false
logo:
  fallback: null
  id: 1520592843159371816
  animated: false
public:
  fallback: 🔓
  id: null
  animated: false
private:
  fallback: 🔒
  id: null
  animated: false
mafia_count:
  fallback: 🐺
  id: null
  animated: false
enable_doctor:
  fallback: 🧑‍🌾
  id: null
  animated: false
enable_detective:
  fallback: 🔎
  id: null
  animated: false
first_move:
  fallback: ⏱️
  id: null
  animated: false
bullet:
  fallback: 🔸
  id: null
  animated: false
difficulty:
  fallback: 📊
  id: 1520592828445753364
  animated: false
bot:
  fallback: null
  id: 1520592823986946209
  animated: false
restart:
  fallback: null
  id: 1520592849253437611
  animated: false
