success:
  fallback: ✅
  id: null
  animated: false
admin:
  fallback: 👑
  id: 1518074105218334741
  animated: false
ban:
  fallback: null
  id: 1518074106480955514
  animated: false
clueless:
  fallback: null
  id: 1518074107718144060
  animated: false
creator:
  fallback: null
  id: 1518074108083044544
  animated: false
error:
  fallback: ❌
  id: 1518074108858990715
  animated: false
explosion:
  fallback: null
  id: 1518074109471363215
  animated: true
facepalm:
  fallback: null
  id: 1518074110511681586
  animated: true
first:
  fallback: null
  id: 1518074111073587312
  animated: false
forward:
  fallback: null
  id: 1518074111803527321
  animated: false
game_mafia:
  fallback: null
  id: 1518074114781347840
  animated: false
github:
  fallback: null
  id: 1518074115691384982
  animated: false
hmm:
  fallback: null
  id: 1518074116673114282
  animated: false
hnn:
  fallback: null
  id: null
  animated: false
join:
  fallback: null
  id: 1518074118233395230
  animated: false
kick:
  fallback: null
  id: 1518074119344619571
  animated: false
last:
  fallback: null
  id: 1518074120087015585
  animated: false
leave:
  fallback: null
  id: 1518074121362083989
  animated: false
loading:
  fallback: null
  id: 1518074122305929276
  animated: true
playcord:
  fallback: null
  id: 1518074124474388641
  animated: false
pointing:
  fallback: null
  id: 1518074125229359104
  animated: false
ready:
  fallback: null
  id: 1518074126894366881
  animated: false
rematch:
  fallback: null
  id: 1518074127620247586
  animated: false
settings:
  fallback: null
  id: 1518074128987586672
  animated: false
space:
  fallback: null
  id: 1518074130166055062
  animated: false
spectate:
  fallback: null
  id: 1518074130853920859
  animated: false
time:
  fallback: null
  id: 1518074132821053561
  animated: false
timer:
  fallback: null
  id: 1518074134045786274
  animated: false
user:
  fallback: null
  id: 1518074134767341690
  animated: false
play:
  fallback: ▶️
  id: null
  animated: false
previous:
  fallback: ◀️
  id: 1518074126173077588
  animated: false
next:
  fallback: ▶️
  id: 1518074123337728080
  animated: false
external_link:
  fallback: 🔗
  id: null
  animated: false
configure:
  fallback: ⚙️
  id: null
  animated: false
tictactoe_x:
  fallback: ❌
  id: null
  animated: false
tictactoe_o:
  fallback: ⭕
  id: null
  animated: false
mafia_villager:
  fallback: 🧑‍🌾
  id: null
  animated: false
mafia_werewolf:
  fallback: 🐺
  id: null
  animated: false
game:
  fallback: null
  id: 1518074113799884861
  animated: false
learn:
  fallback: null
  id: 1518074120934527177
  animated: false
